"""Split offline renders into shared bodies and small expression patches."""
from pathlib import Path
import json
import sys
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"
HD = "--hd" in sys.argv
SIZE = 576 if HD else 192
STATES = ["idle", "happy", "love", "surprise", "sleep", "blink", "off", "computer",
          "computer-0", "computer-1", "computer-2", "computer-3"]
YAW_COUNT = 36
PITCHES = [-12, 0, 12, 24]


def main():
    prefix = "hd-" if HD else ""
    sheet = None if HD else Image.open(ASSETS / "rendered.png").convert("RGBA")
    count = YAW_COUNT*len(PITCHES)
    if not HD:
        assert sheet.size == (SIZE*len(STATES), SIZE*count)
    entries = []
    header = ["// Generated by tools/prepare_assets.py", "#pragma once",
              "struct SpriteLayout { int x, y, width, height; };", "inline constexpr int kSpriteSize = 192;",
              f"inline constexpr int kYawCount = {YAW_COUNT}, kPoseCount = {count}, kFaceCount = {len(STATES)};",
              "inline constexpr SpriteLayout kLayouts[] = {"]
    if HD:
        header = ["// Generated by tools/prepare_assets.py --hd", "#pragma once", '#include "layout.h"',
                  f"inline constexpr int kHdSpriteSize = {SIZE};", "inline constexpr SpriteLayout kHdLayouts[] = {"]
    resources = ["// Generated by tools/prepare_assets.py"]
    for view in range(count):
        if HD and view % YAW_COUNT == 0:
            if sheet is not None:
                sheet.close()
            sheet = Image.open(ASSETS / f"hd-rendered-{view//YAW_COUNT}.png").convert("RGBA")
            assert sheet.size == (SIZE*len(STATES), SIZE*YAW_COUNT)
        row = view % YAW_COUNT if HD else view
        frames = [sheet.crop((i*SIZE, row*SIZE, (i+1)*SIZE, (row+1)*SIZE)) for i in range(len(STATES))]
        alpha = np.array(frames[0])[:, :, 3]
        assert not (alpha[0].any() or alpha[-1].any() or alpha[:, 0].any() or alpha[:, -1].any()), f"Clipped pose {view}"
        base = np.array(frames[6])
        difference = np.any(np.stack([np.array(f) != base for f in frames]), axis=(0, 3))
        ys, xs = np.where(difference)
        box = (int(xs.min()), int(ys.min()), int(xs.max()+1), int(ys.max()+1)) if len(xs) else (0,0,1,1)
        x, y, right, bottom = box
        width, height = right-x, bottom-y
        patches = Image.new("RGBA", (width*len(STATES), height))
        for i, frame in enumerate(frames):
            patches.paste(frame.crop(box), (i*width, 0))
        frames[6].save(ASSETS / f"{prefix}body-{view}.png")
        patches.save(ASSETS / f"{prefix}faces-{view}.png")
        for i, frame in enumerate(frames):
            rebuilt = frames[6].copy()
            rebuilt.paste(patches.crop((i*width, 0, (i+1)*width, height)), (x, y))
            assert np.array_equal(np.array(rebuilt), np.array(frame)), "Patch reconstruction changed pixels"
        header.append(f"    {{{x}, {y}, {width}, {height}}},")
        entries.append({"view": view, "patch": [x,y,width,height]})
        resource = (1001 if HD else 201)+view*2
        resources.extend([f'{resource} RCDATA "assets/{prefix}body-{view}.png"', f'{resource+1} RCDATA "assets/{prefix}faces-{view}.png"'])
    header.append("};\n")
    (ASSETS / f"{prefix}layout.h").write_text("\n".join(header), encoding="ascii")
    (ASSETS / f"{prefix}poses.rc").write_text("\n".join(resources)+"\n", encoding="ascii")
    if not HD:
        icon = sheet.crop((0, SIZE*YAW_COUNT, SIZE, SIZE*(YAW_COUNT+1)))
        icon.save(ASSETS / "pico.ico", sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(192,192)])
    (ASSETS / f"{prefix}manifest.json").write_text(json.dumps({"sourceSize":SIZE,"states":STATES,"yawCount":YAW_COUNT,"pitches":PITCHES,"views":entries},indent=2)+"\n")
    print(f"Verified lossless reconstruction of all {count*len(STATES)} frames.")


if __name__ == "__main__":
    main()
